serial_port: "/dev/cu.usbmodem101"
ad_channel_index: 0
ad_enabled: false
ad_interval_seconds: 10800
ad_text: "Join a growing local user group! https://upstatemesh.net"
beacon_channel_index: 1
beacon_enabled: true
beacon_interval_seconds: 900
beacon_text: "Beep!"
weather_channel_index: 2
weather_enabled: true
weather_interval_seconds: 3600
